language: python
sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  # TODO: - luarocks install luacheck
  - luarocks install busted

script:
  # TODO: - luacheck --no-unused-args --std max+busted lua
  - npm install

  # hack - support older node versions
  - ./node_modules/.bin/buble ./frontend/Lantern.js > ./frontend/Lantern.js
  - ./node_modules/.bin/buble ./frontend/test.js > ./frontend/test.js

  - npm test
  - cd hardware
  - busted --verbose test/test.lua
