language: python
sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  # TODO: - luarocks install luacheck
  - luarocks install busted

script:
  # TODO: - luacheck --no-unused-args --std max+busted lua
  - cd hardware
  - busted --verbose test/test.lua
